services:
  GRBOX Panel:
    image: ghcr.io/mhsanaei/GRBOX Panel:latest
    container_name: GRBOX Panel
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/GRBOX Panel/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped
